export const enum VNODE_FLAGS {
  // html 标签
  ELEMENT_HTML = 1,
  // svg标签
  ELEMENT_SVG = 1 << 1,
  // 普通有状态组件
  COMPONENT_STATEFULL_NORMAL = 1 << 2,
  // 需要keepalive的组件
  COMPONENT_STATEFULL_SHOULD_KEEP_ALIVE = 1 << 3,
  // 已经keepalive的组件
  COMPONENT_STATEFULL_KEPT_ALIVE = 1 << 4,
  // 函数式组件
  COMPONENT_FUNCTIONAL = 1 << 5,
  TEXT = 1 << 6, //纯文本
  FRAGMENT = 1 << 7,
  PORTAL = 1 << 8,
  ELEMENT = VNODE_FLAGS.ELEMENT_HTML | VNODE_FLAGS.ELEMENT_SVG, // 标签元素
  COMPONENT_STATEFULL = VNODE_FLAGS.COMPONENT_STATEFULL_KEPT_ALIVE |
    VNODE_FLAGS.COMPONENT_STATEFULL_NORMAL |
    VNODE_FLAGS.COMPONENT_STATEFULL_SHOULD_KEEP_ALIVE,
  COMPONENT = VNODE_FLAGS.COMPONENT_STATEFULL | VNODE_FLAGS.COMPONENT_FUNCTIONAL
}
